version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`
      - ./gradlew bootJar
artifacts:
  files:
    - build/libs/gradle-spring-boot-demo.jar
